name: spotify-tracks-to-bigquery

on:
  schedule:
    - cron: "55 */3 * * *"   # every 3 hours (UTC)
  workflow_dispatch: {}      # allow manual trigger

jobs:
  run-spotify-tracks-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Spotify tracks ETL
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python etl/spotify_tracks_to_bigquery.py
